title: mrbang
subtitle: mrbang-00의 블로그입니다. 
description: >- # this means to ignore newlines until "baseurl:"
  블로그 정보입니다.

url: "https://mrbang-00.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Mrbang
author_bio: Mrbang의 블로그입니다. :D
author_email: "bang7233@gmail.com"
author_location: South Korea
author_website_url: "https://github.com/mrbang-00/mrbang-00.github.io"
typewrite-text: 백팩킹, 등산, 캠핑, 이야기, 자전거, 하이킹, 보드게임, 레고, 키보드

# Experiences
author_work_experiences:
            - company_name: BackEnd DEVELOPER
             company_logo: dev.jfif
              # company_url: https://google.com
              designation: Software Engineer
              description: BackEnd DEVELOPER
              visibility: true
            # - company_name: .
            #   company_logo: .
            #   company_url: .
            #   designation: Azure Developer
            #   description: Worked on various Azure Cloud Products
            #   visibility: true

# Education
author_education_details:
              - college_logo: bu.png
                college_name: BAEKSEOK UNIVERSITY
                college_url: https://www.bu.ac.kr/
                # college_degree: 
                # description: Bachelor of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: mrbang-00
github_username:  mrbang-00
facebook_username: mrbang-00
linkedin_username: mrbang-00
behance_username: mrbang-00
instagram_username: mrbang-00
medium_username: mrbang-00
telegram_username: mrbang-00
dribbble_username: mrbang-00
flickr_username: mrbang-00

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: mrbang-00

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 18550d09-b111-4bcc-ab30-d55430db6dbe
formspree_email: bang7233@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
google_analytics: 'G-JC9LLCL1CX'